#!/usr/bin/env bash
# Recreate out/*/xcode_links after an out-cache restore.
#
# The symlink tree is excluded from S3 (aws s3 sync cannot mirror the SDK's
# recursive/broken links). Restored build.ninja still references
# xcode_links/electron/MacOSX*.sdk/.../exc.defs — without the link, gn gen
# fails with "Input to targets not generated by a dependency" and ninja cannot
# compile. Point the stamped SDK name at the runner's live SDKROOT.
#
# Usage: ensure-xcode-links.sh <out_dir>
set -euo pipefail

OUT_DIR="${1:?out_dir required}"
ARGS_GN="${OUT_DIR}/args.gn"
LINK_DIR="${OUT_DIR}/xcode_links/electron"

if [ ! -d "$OUT_DIR" ]; then
  echo "ensure-xcode-links: missing $OUT_DIR" >&2
  exit 1
fi

SDK_ROOT="$(xcrun --show-sdk-path)"
test -d "$SDK_ROOT" || { echo "ensure-xcode-links: SDKROOT missing: $SDK_ROOT" >&2; exit 1; }

SDK_NAME="MacOSX.sdk"
if [ -f "$ARGS_GN" ]; then
  # mac_sdk_path = "//out/Release/xcode_links/electron/MacOSX26.4.sdk"
  extracted="$(sed -n 's/.*xcode_links\/electron\/\([^"/]*\)".*/\1/p' "$ARGS_GN" | head -1 || true)"
  if [ -n "$extracted" ]; then
    SDK_NAME="$extracted"
  fi
fi

mkdir -p "$LINK_DIR"
ln -sfn "$SDK_ROOT" "${LINK_DIR}/${SDK_NAME}"

DEFS="${LINK_DIR}/${SDK_NAME}/usr/include/mach/exc.defs"
if [ ! -f "$DEFS" ]; then
  echo "ensure-xcode-links: missing $DEFS (link target $SDK_ROOT)" >&2
  ls -la "$LINK_DIR" >&2 || true
  exit 1
fi

echo "xcode_links: ${LINK_DIR}/${SDK_NAME} -> ${SDK_ROOT}"
